### ISSUE TITLE
is the v4 branch ready to use?

### ISSUE THREAD

**Issue by opensensesolutions** [fullcalendar/webpack-example#2]
I'm new to this so sorry if I'm doing something stupid, but with the v4 branch
npm install 
fails with:
 '@fullcalendar/core' is not in the npm registry 
or instead of core, daygrid/timegrid/list ( it seems to randomize the loading order ) , so all the dependencies in package.json

The same thing happens with the scheduler-webpack-example v4 branch as well.

npm ERR! Linux 4.15.0-45-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Not found : @fullcalendar/core
npm ERR! 404 
npm ERR! 404  '@fullcalendar/core' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'fullcalendar-webpack-example'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/fcs/webpack-example-4/npm-debug.log

[npm-debug.log](https://github.com/fullcalendar/webpack-example/files/2823275/npm-debug.log)

**Comment by arshaw** [comment]
it should work now!

https://fullcalendar.io/blog/2019/02/v4-beta-release

**Comment by opensensesolutions** [comment]
I had to change all the beta.1 instances to beta.2 in package.json, otherwise I got errors like this:

npm ERR! No compatible version found: @fullcalendar/daygrid@4.0.0-beta.1
npm ERR! Valid install targets:
npm ERR! 4.0.0-beta.2

But after doing that it is working, thanks!

**Comment by arshaw** [comment]
i updated the v4 branch of this repo with the latest deps in package.json. it uses beta.4 now. hope that helps!

**Comment by maettyhawk** [comment]
@arshaw: I'm getting the following error:

fullcalendar.js:6601 Uncaught TypeError: Cannot read property 'el' of undefined
    at Calendar.dispatch (fullcalendar.js:6601)
    at Calendar.setOption (fullcalendar.js:6745)
    at HTMLDocument.<anonymous> (fullcalendar.js:8505)

Steps to reproduce:
* clone v4 branch
* execute "npm i"
* execute "npm run build"
* run test server (i used http-server)
* open index.html and see console in debug bar

**Comment by arshaw** [comment]
v4 is ready! been ready for a while
